---
title: "Figures"
author: "Niklas Hausmann"
date: '2022-08-19'
output:
  pdf_document: default
  word_document: default
---
# Libraries 
```{r Libraries,echo=FALSE,message = FALSE,warning = FALSE}
knitr::opts_chunk$set(echo=FALSE,message = FALSE,warning = FALSE)

{
  pacman::p_load(
    here,
    janitor,ggpubr,
    tidyverse,
    cowplot,ggx,ggeasy,giscoR,sf,
    patchwork,ggbeeswarm,
    RColorBrewer) 
  source(here("geom_flat_violin.R"))
  theme_set(theme_cowplot())
}
```

# Data
```{r Data}
Shells <- readRDS(here("data","Shells"))

```

#Figure Spectrum
```{r Figure Spectrum}

Spot1sum <- read_csv(here("data","KP-AP_20210917_M_TEST_raw_data.csv"),
                  col_names = FALSE) %>%
  pivot_longer(cols=everything() ,names_to="pixel", values_to="intensity") %>%
  mutate(spec=rep(1:102,each=1024)) %>% 
  filter(spec<101) %>%
  group_by(pixel) %>% 
  summarise(intensity=mean(intensity)) %>% 
  mutate(pixel=as.numeric(gsub("X","",pixel))) %>% 
  arrange(pixel)

Spot1_WL <- read_csv(here("data","KP-AP_20210917_M_TEST_raw_data.csv"),
                  col_names = FALSE) %>% 
  slice(102) %>% 
  t() %>% 
  as.tibble() %>% 
  mutate(pixel=as.numeric(rownames(.)))%>% 
  rename(wavelength=V1)

Spot1sum <- Spot1sum %>% 
  left_join(Spot1_WL,by = "pixel")


 fig_spec <- 
  Spot1sum %>% 
  ggplot()+
  aes(wavelength,intensity)+
  # geom_vline(xintercept = c(279.41,280.1,285.05,300.6,315.9,318),linetype = "longdash", size=0.25)+
  geom_segment(aes(x=279.41,xend=279.41,y=24000,yend=0),inherit.aes = FALSE,linetype = "longdash", size=0.25)+
  geom_segment(aes(x=280.1,xend=280.1,y=27000,yend=0),inherit.aes = FALSE,linetype = "longdash", size=0.25)+
  geom_segment(aes(x=285.05,xend=285.05,y=27000,yend=0),inherit.aes = FALSE,linetype = "longdash", size=0.25)+
  geom_segment(aes(x=300.6,xend=300.6,y=27000,yend=0),inherit.aes = FALSE,linetype = "longdash", size=0.25)+
  geom_segment(aes(x=315.9,xend=315.9,y=27000,yend=0),inherit.aes = FALSE,linetype = "longdash", size=0.25)+
  geom_segment(aes(x=317.96,xend=317.96,y=27000,yend=0),inherit.aes = FALSE,linetype = "longdash", size=0.25)+
  annotate("Text", x = 278.9, y = 22500, label = "*Mg II",col = "black", size = 5,angle = 90)  +
  annotate("Text", x = 279.5, y = 26000, label = "Mg II",col = "black", size = 5,angle = 90)  +
  annotate("Text", x = 284.5, y = 26000, label = "Mg I",col = "black", size = 5,angle = 90)  +
  annotate("Text", x = 300.1, y = 26000, label = "Ca I",col = "black", size = 5,angle = 90)+
  annotate("Text", x = 315.4, y = 25900, label = "*Ca II",col = "black", size = 5,angle = 90)+
  annotate("Text", x = 317.46, y = 26000, label = "Ca II",col = "black", size = 5,angle = 90)+
  # geom_area(show.legend=FALSE,fill="white") +
  geom_ribbon(aes(ymin=-5000, ymax=intensity),fill="white")+
  geom_path(show.legend=FALSE) +
  labs(y="Intensity (a.u.)", 
       x="Wavelength (nm)")+
  coord_cartesian(ylim=c(0, 28000))

fig_spec

```


# Map of samples
```{r Map of samples}

Countries <-
  gisco_get_countries(
    country = c("Greece", "Albania", "North Macedonia", "Turkey"),
    # region = c("Europe", "Asia"),
    resolution = "1"
  )


Points <- tibble::tribble(
                                         ~Location,              ~Lat,               ~Long, ~Number,
              "Pyrgos Apollonias, Pangaio, Kavala",   40.7402079481488,        24.14294391, 1,
  "Ν. Kallikrateia, Chalkidiki, Mykoniatika beach",   40.3013436847067,   23.0862692611319, 2,
                               "Franchthi Paralia",   37.4228089933264,   23.1308463375217, 9, 
                                    "Alyko, Naxos",   36.9848604928337,   25.3856107492044, 11,
                        "“Gremos”, Ysterni, Paros",   37.0877707264391,   25.2644206583826, 10,
                           "Kedrodasos, SW Chania",   35.2684489949304,   23.5588659182893, 13,
                             "Glaros, NE Rethymno",   35.4131005139213,        24.82722545, 14,
                       "Ligres, Southern Rethymno",    35.134817825275,        24.53191672, 15,
                             "Monemvasia, Laconia",          36.686718,          23.037834, 12,
                            "Youra, southern dock",   39.3686180522032,        24.14602087, 8,
                "Agios Petros islet, Kyra-Panagia",   39.3212721037396,        24.05445331, 7,
                             "Patitiri, Alonnisos",   39.1428550211811,        23.86363465, 6,
                    "Koropi beach, Pagasetic Gulf",     39.28927338458,        23.14363292, 4, 
             "Katiyorgis beach, Aegean sea, Volos",   39.1725588453517,        23.34283486, 5,
                                   "Plakes, Volos",            39.3475,            22.9725, 3
  ) %>% 
  # # arrange(-Lat) %>%
  # mutate(number=row_number()) %>% 
  clean_names()


Map <- 
ggplot() +
  geom_sf(
    data = Countries, 
    fill = "grey90",
    colour = "white"
  ) +
  geom_sf(
    data = Countries %>% filter(NAME_ENGL == "Greece"),
    fill = "grey80",
    colour = "grey30"
  ) +
  geom_point(data = Points,
             aes(x = long , y = lat),
             col = "firebrick4",
             size = 2) +
  geom_text(data = Points %>% filter(number!=3,number!=11,number!=8),
            aes(
                x = long,
                y = lat,
                label = number
                ),
            vjust = -0.5,
            size= 8
            ) +
   geom_text(data = Points %>% filter(number==11|number==8), 
            aes(
                x = long,
                y = lat,
                label = number
                ),
            vjust = -0.5,
            hjust = -0.1,
            size= 8
            ) +
    geom_text(data = Points %>% filter(number==3), 
            aes(
                x = long,
                y = lat,
                label = number
                ),
            vjust = -0.5,
            hjust = 0.4,
            size= 8
            ) +
  labs(x = "Longitude", y = "Latitude") +
  coord_sf(
    xlim = c(20, 27),
    ylim = c(35, 41)
  )+
  theme_cowplot(20)

map

ggsave(map,here("map.png"),dpi = "retina")

```

#Stats Elemental Maps

## Stat Plots
```{r Plots Map Statistics}
  Area <- 
  Summary_Shells %>% 
    ggplot()+
    aes(x=as.factor(res),y=area_mm,col=as.factor(res))+
    ggbeeswarm::geom_beeswarm(show.legend = FALSE,cex = 1.2,)+
    labs(x="Resolution",y=expression('Sample Area in' ~ 'mm'^2))+
      scale_color_brewer(palette = "Paired")+

      ggtitle("", subtitle="Sampled area by resolution")+theme_cowplot(25)


N_Points <-  
 Summary_Shells %>%
ggplot()+
  aes(x=as.factor(res),y=n_points)+
  ggbeeswarm::geom_beeswarm(aes(col=as.factor(res)),cex = 1.2, show.legend = FALSE)+
  labs(x="Resolution",y= "Number of Points")+
      scale_color_brewer(palette = "Paired")+

  ggtitle("", subtitle="Number of points by resolution")+theme_cowplot(25)
  

  
  Time <- 
  Summary_Shells %>% 
    ggplot()+
    aes(x=as.factor(res),y=time,col=as.factor(res))+
    ggbeeswarm::geom_beeswarm(show.legend = FALSE,cex = 1.2,)+
    labs(x="Resolution",y="Time in minutes")+
      scale_color_brewer(palette = "Paired")+

    ggtitle("", subtitle="Time of analysis by resolution")+theme_cowplot(25)

  
Area+N_Points+Time+plot_annotation(tag_levels = 'A')


ggsave2(
  filename = "Distributions_time-area.png",
  
  units = "cm",
  width = 45,
  height = 15
)

```




## Plot Mg/Ca distribution for all data (not actually helpful without showing the aragonitic layers as well)
```{r distribution mineral}

Elemental_distribution <- Shells %>%
  select(mg_ca) %>%
  filter(mg_ca < 2) %>% # we reduced this number to 2 because occasional outliers exist in the dataset, which would increase the upper limits unnecesarilly
  sample_n(20000) %>%  # this creates a random sub-sample of all measurements (total of 900k)
  ggplot() +
  aes(x = "", y = mg_ca, col = mg_ca) +
  geom_beeswarm(
    side = 1L,
    size = 0.5,
    show.legend = FALSE,
    priority = "none"
  ) +
  viridis::scale_color_viridis(option = "G") +
  annotate(
    "text",
    x = 5.8,
    y = 0.275,
    label = "Aragonite",   size = 8,
    colour = "black"
  ) +
  annotate(
    "segment",
    x = 5.5,
    xend = 5.5,
    y = 0.04,
    yend = 0.5,
    colour = "black",
    size = 1,
    alpha = 0.6
  ) +
  annotate(
    "segment",
    x = 5.5,
    xend = 5.3,
    y = 0.5,
    yend = 0.5,
    colour = "black",
    size = 1,
    alpha = 0.6
  ) +
  annotate(
    "segment",
    x = 5.5,
    xend = 5.3,
    y = 0.04,
    yend = 0.04,
    colour = "black",
    size = 1,
    alpha = 0.6
  ) +
  geom_blank(aes(x=12.5))+ 
  annotate(
    "text",
    x = 11.8,
    y = 1.3,
    label = "Calcite",    size = 8,

    colour = "black"
  ) +
  annotate(
    "segment",
    x = 11.5,
    xend = 11.5,
    y = 0.55,
    yend = 2,
    colour = "black",
    size = 1,
    alpha = 0.6
  ) +
  annotate(
    "segment",
    x = 11.5,
    xend = 11.3,
    y = 2,
    yend = 2,
    colour = "black",
    size = 1,
    alpha = 0.6
  ) +
  annotate(
    "segment",
    x = 11.5,
    xend = 11.3,
    y = 0.55,
    yend = 0.55,
    colour = "black",
    size = 1,
    alpha = 0.6
  ) +
  
  coord_flip() +
  labs(x = "", y = "Mg/Ca Intensity Ratio") +
  ggtitle("Common distribution of Mg/Ca intensity ratios between minerals")

Elemental_distribution+theme_cowplot(20)

ggsave2(
  filename = "Elemental_distribution.png",
  
  units = "cm",
  width = 30,
  height = 20
)

```

#Make nice map fir KP-AP F
```{r KP-AP_F}

Shell_Map <-
  Shells %>% 
    filter(
           !grepl("LINE",filename),
           !grepl("CORNER",filename),
            mg_ca<2) %>% 
    filter(grepl("KP-AP_20210917_F",filename)) %>%
  mutate(y=if_else(grepl("POST",filename),y+3,if_else(grepl("ANT",filename),y-3,y))) %>% 
    unite(col = "sitespecimen",c(site,specimen),sep="_") %>% 
  ggplot()+
  aes(y,
      x,
      col=mg_ca,
      fill = mg_ca
    ) +
  theme(panel.background = element_rect(fill = 'white'))+
  geom_tile(data=. %>% filter(res==30, !grepl("ANT",filename)), show.legend = FALSE)+ 
  geom_tile(data=. %>% filter(res==30, !grepl("POST",filename)), show.legend = FALSE)+
  geom_tile(data=. %>% filter(res==100), height = 0.1, width=0.1, show.legend = FALSE)+
 
  viridis::scale_fill_viridis(option = "G")+
  viridis::scale_color_viridis(option = "G")+
  coord_fixed()+
  labs(x= "X coordinate (mm)", y = "Y coordinate (mm)", fill = "Mg/Ca")+
  annotate("text", label="30 µm resolution ", x= -10, y= 0,hjust = "left", size=5)+
  annotate(geom = "curve", x = -10, y = -0.5, xend = -10, yend = -5,
    curvature = 0.2, arrow = arrow(length = unit(2, "mm")))+
  annotate("text", label="100 µm resolution ", x= 5, y= -2,hjust = "centre", size=5)+
  annotate(geom = "curve", x = 5, y = -2.5, xend = -4, yend = -5,
    curvature = -0.2, arrow = arrow(length = unit(2, "mm")))+
  ggtitle("Mg/Ca ratios in limpet shell")


ggsave2(
  filename = "Shell_Map.png",
  plot = Shell_Map,
  units = "cm",
  width = 21,
  height = 14
)


```



# SEM
## Data
```{r data}

read_plus <- function(flnm) {
    read_csv(flnm,col_names = FALSE) %>% 
        mutate(filename = flnm)
}

Lines <-
  list.files(
    path = here("data", "line_data"),
    pattern = c("*.csv"),
    recursive = TRUE
  ) %>%
  map_df( ~ read_plus(here("data", "line_data", .))) %>%
  mutate(
    order = gsub("[[:punct:]]", "", gsub(
      "[^0-9.-]",
      "",
      gsub(
        x = filename,
        pattern = paste0(here("data"), "/"),
        replacement = ""
      )
    )),
    order = as.numeric(order),
    side = if_else(order < 6, "inner", "outer")
  ) %>%
  select(-filename) %>%
  rename(
    x = X1,
    y = X2,
    z = X3,
    mg_ca = X4,
    std = X5,
    rstd = X6
  ) %>% 
  group_by(order) %>% 
  mutate(sequence = ifelse(side=="outer",row_number()-n(),(row_number()-1)*-1)) %>% 
  ungroup()

Line_Spectra <- list.files(
    path = here("data", "line spectra"),
    pattern = c("*.csv"),
    recursive = TRUE
  ) %>%
  map_df( ~ read_plus(here("data", "line spectra", .))) %>% 
  select(-X3,-filename) %>% 
    rename(wavelength = X1,
         intensity = X2) %>%  
  mutate(line = as.factor(3),
         sequence = as.factor(rep(c(1,2,3,6),each = 1024)),
         location = as.factor(rep(c("on flat section", "on flat section", "on edge", "off shell"),each=1024))) 

```

## Plots (SEM IMAGE)
```{r line plots}

img <- magick::image_read("edge_values.png")

A <- ggplot()+
  geom_blank()+
  theme_void()+ggpubr::background_image(img)


B <- 
Lines %>% 
  filter(order>2) %>% 
  filter(side=="inner") %>% 
  mutate(location = ifelse(sequence+6<3,"on flat section", ifelse(sequence+6<4,"on edge", "off shell"))) %>%
  ggplot()+
  aes(group=order, col=location)+
  geom_smooth(aes(sequence+6,rstd*100),formula = y~x, method = 'loess', inherit.aes = FALSE,size=0, fill="grey80")+
  geom_point(aes(x=sequence+6,y=rstd*100), show.legend = FALSE, size=3)+
  geom_vline(xintercept = 3, linetype = "longdash", alpha = 0.5)+
  annotate("text", label="edge values ", x= 2, y= 15,hjust = "centre", size=3)+
  annotate(geom = "curve", x = 2, y = 14.5, xend = 2.8, yend = 10, 
    curvature = 0.2, arrow = arrow(length = unit(2, "mm"))
  )+
  scale_x_continuous(breaks = c(1,2,3,4,5,6))+
  scale_color_brewer(palette = "Set2")+
  theme_cowplot(10)+
  labs(x= "Sequential sample points",
       y="Relative standard deviation in %")


C <- 
Line_Spectra %>% 
  ggplot()+
  aes(wavelength,intensity, col=location, group=sequence)+
  geom_path()+
  scale_color_brewer(palette = "Set2")+
  theme_cowplot(10)+
  theme(legend.position = c(0.15,0.8))+
  labs(col= "Sample location", y="Intensity (a.u.)", x="Wavelength (nm)")





Fig_edge <- A+theme(plot.tag.position  = c(.03, .98), plot.tag = element_text(color = "white", face="bold"))+
  B+theme(plot.tag.position  = c(.03, .98))+
            C+theme(plot.tag.position  = c(.03, .98))+
                      plot_annotation(tag_levels = "A")+plot_layout(width = c(0.4,0.3,0.3))

ggsave2(
  filename = "Fig_Edge.png",
  plot = Fig_edge,
  units = "cm",
  width = 21,
  height = 14
)


```

